export const projects = [
  {
    id: 0,
    title: "BTP Dashboard",
    description: "Dashboard for a E-commerce website for the EU market",
    image: "./images/BTP.png",
    // github:"https://github.com/MehidGN/B.CTech",
    live: "",
    tech: "Next-js Tailwind-Css ShadCn",
  },
  {
    id: 7,
    title: "Draft Backend",
    description:
      "Platform for scouting Players (football, basketball, handball)",
    image: "./images/draft.png",
    // github:"https://github.com/MehidGN/B.CTech",
    live: "",
    tech: "Node-js Express-js Sequelize SQL",
  },
  {
    id: 7,
    title: "TijaraTok",
    description: "E-commerce management Platform for the Algerian market",
    image: "./images/tijaratok.png",
    // github:"https://github.com/MehidGN/B.CTech",
    live: "",
    tech: "React-js Tailwind-Css ",
  },
  {
    id: 1,
    title: "B.CTech",
    description: "landing page for a Blockchain and cryptocurrency project",
    image: "./images/BTech.png",
    github: "https://github.com/MehidGN/B.CTech",
    live: "",
    tech: "React-Js Sass",
  },
  {
    id: 2,
    title: "LAMASTORE",
    description: "website for an e-commerce clothes brand",
    image: "./images/lamastor.png",
    github: "https://github.com/MehidGN/E-commerce-Clothes-Website-",
    live: "",
    tech: "React-Js Sass Stripe Redux",
  },
  {
    id: 3,
    title: "IMBb clone",
    description: "Website fot tracking movies Rate",
    image: "./images/imb.png",
    github: "https://github.com/MehidGN/IMBb-Clone",
    live: "",
    tech: "Next-Js Tailwind-Css",
  },
  {
    id: 4,
    title: "Ideatech",
    description: "description",
    image: "./images/ideatech.png",
    github: "https://github.com/MehidGN/ideathon-estin",
    live: "https://bytecraft-ideatech.web.app/",
    tech: "React-js Tailwind-Css",
  },
  {
    id: 5,
    title: "Three Js Portfolio",
    description: "portfolio with 3D models using Three Js",
    image: "./images/threjs.png",
    github: "https://github.com/MehidGN/Modern-portfolio-ThreeJS",
    live: "https://modern-portfolio-three-js.vercel.app/",
    tech: "Three-Js Styled-Components",
  },
  {
    id: 6,
    title: "CoursDZ",
    description: "Platform for courses using web scraping",
    image: "./images/coursDz.png",
    github: "https://github.com/MehidGN/GL-Project",
    live: "",
    tech: "React Tailwind Django",
  },
];

export const smallProjects = [
  {
    id: 1,
    title: "GYM Task Manager",
    description: "website for managing Gym sessions using the MERN stack",
    image: "./images/gym.png",
    github: "https://github.com/MehidGN/Gym-Tasks-manager-full-stack-website",
    live: "",
    tech: "React-Js Tailwind MongoDb Express-Js Node-Js",
  },
];
